# Generated by Django 2.2 on 2019-05-07 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_specs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dp',
            field=models.ImageField(default='profile_pic/default.jpg', upload_to='profile_pic/'),
        ),
    ]
